In [31]:
import cv2
import numpy as np
import math
img = cv2.imread('aun.jpeg',0)
# d = cv2.imwrite('gray.jpeg',img)
# gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img)
# img = np.array([[1,2,3,8],[4,5,6,8],[7,8,9,8],[1,2,3,8]])
# print(img)

# key = input()
key = 'aunali'
# print(key)
x = img.shape[0]
cols = img.shape[1]
l = len(key)
# print(co)
x2 = x*(math.ceil(float(cols) / float(l) ))
img2 = np.full(((x2), l), 0)
print(img2)

# for i in range(cols):
#     for j in range(key.length()):


[[225 225 225 ... 216 210 132]
 [225 225 225 ... 216 210 132]
 [225 225 225 ... 216 210 132]
 ...
 [ 34  35  36 ...  13  12   9]
 [ 33  36  38 ...  14  12   8]
 [ 32  36  39 ...  14  12   8]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 ...
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [33]:
import cv2
import numpy as np
import math
img = cv2.imread('aun.jpeg',0)
print(img)

new = np.ravel(img)
print(new)

[[225 225 225 ... 216 210 132]
 [225 225 225 ... 216 210 132]
 [225 225 225 ... 216 210 132]
 ...
 [ 34  35  36 ...  13  12   9]
 [ 33  36  38 ...  14  12   8]
 [ 32  36  39 ...  14  12   8]]
[225 225 225 ...  14  12   8]
