In [44]:
import math
import random

In [45]:
p = 19  #prime no.1
q = 13  #prime no.2

def gen_public_key(p,q):
    n = p*q
    phi_n = (p-1)*(q-1)
    # e = math.randint(1,phi_n)
    # e = random.randint(1,10)
    e = 5
    # print(e)
    return(n,e)

In [46]:
def gen_priv_key(p,q,e):
    phi_n = (p-1)*(q-1)
    # k = random.randint(1,100).
    k = 4
    d = (k*phi_n + 1)/e
    print("d is ",d)
    d = int (d)
    return d

In [47]:
n , e = gen_public_key(p,q)
# print(n,e)
d = gen_priv_key(p,q,e)
# print(d)
data = 225
# data = 89

enc = (data**e)%n
print(enc)

dec = (enc**d)%n 
print(dec)

d is  173.0
23
225


In [56]:
import cv2
import numpy as np
img = cv2.imread('../exp2/aun.jpeg',0)
img_flat = img.flatten()
print(img_flat)

for i in range(len(img_flat)):
    if (img_flat[i] > 246):
            img_flat[i] = 246

# for i in range(574):
#     for j in range(574):
#         if (img[i][j] > 246):
#             img[i][j] = 246

print(img_flat)

enc_img_flat = np.copy(img_flat) 

for i in range(len(enc_img_flat)):
    enc_img_flat[i] = (int(enc_img_flat[i])**e)%n

enc_img = enc_img_flat.reshape((574,574))
print(enc_img)

# for i in range(574):
#     for j in range(574):
#         enc_img[i][j] = (enc_img[i][j]**e)%n

# print(enc_img.shape)
# print(enc_img)

# cv2.imwrite('enc_img.jpeg',enc_img)


dec_img_flat = np.copy(enc_img_flat)


for i in range(len(dec_img_flat)):
    dec_img_flat[i] = (int(dec_img_flat[i])**d)%n

dec_img = dec_img_flat.reshape((574,574))
print(dec_img)


# for i in range(574):
#     for j in range(574):
#         dec_img[i][j] = (enc_img[i][j]**d)%n
# print(dec_img)
cv2.imwrite('dec_img.jpeg',dec_img)


[225 225 225 ...  14  12   8]
[225 225 225 ...  14  12   8]
[[ 23  23  23 ... 125  58 227]
 [ 23  23  23 ... 125  58 227]
 [ 23  23  23 ... 125  58 227]
 ...
 [ 21  42  82 ...  52 103  16]
 [219  82  38 ... 105 103 164]
 [223  82  39 ... 105 103 164]]
[[225 225 225 ... 216 210 132]
 [225 225 225 ... 216 210 132]
 [225 225 225 ... 216 210 132]
 ...
 [ 34  35  36 ...  13  12   9]
 [ 33  36  38 ...  14  12   8]
 [ 32  36  39 ...  14  12   8]]


True